name: CI

on: [push]

jobs:
  build:
    name: PHP ${{ matrix.php }} (${{ matrix.os }})

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        php: [ 8.1, 8.2, 8.3 ]
        os: [ ubuntu-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php }}

      - name: Show Php Version
        run: php -v

      - name: Composer Install
        run: composer install --prefer-dist --ignore-platform-reqs --no-cache

      - name: PHP Spec
        run: ./vendor/bin/phpspec run --format=dot
